export const MenuItems = [
  {
    title: "History",
    path: "/history",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "What can PCCI do for you",
    path: "/what-can-pcci-do-for-you",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Board Of Directors",
    path: "/board-of-directors",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Secretariat",
    path: "/secretariat",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Contact Us",
    path: "/contact-us",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Agriculture and Fishery",
    path: "/advocacy/agriculture-and-fishery",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Banking and Capital Formation",
    path: "/advocacy/banking-and-capital-formation",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Corporate Governance",
    path: "/advocacy/corporate-governance",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Energy and Power",
    path: "/advocacy/energy-and-power",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Industry and Trade",
    path: "/advocacy/industry-and-trade",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Infrastructure",
    path: "/advocacy/infrastructure",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Innovation and Science and Technology",
    path: "/advocacy/innovation-and-science-and-technology",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Intellectual Property",
    path: "/advocacy/intellectual-property",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Legislation and Taxation",
    path: "/advocacy/legislation-and-taxation",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Mining and Mineral Resources",
    path: "/advocacy/mining-and-mineral-resources",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Sustainable Development Goals",
    path: "/advocacy/sustainable-development-goals",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Transport Logistics",
    path: "/advocacy/transport-logistics",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Urban Housing Development",
    path: "/advocacy/urban-housing-development",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Youth",
    path: "/advocacy/youth",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "PCCI Innovation Center",
    path: "https://innovate.com.ph/",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Asia Business Creation Platform",
    path: "https://www.abc-pf.org/ph/?wovn=en",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Business Councils",
    path: "/business-councils",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Africa",
    path: "/africa",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "America",
    path: "/america",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Asia",
    path: "/asia",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Europe",
    path: "/europe",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Middle East",
    path: "/middle-east",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Oceania",
    path: "/oceania",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "ICC",
    path: "https://iccwbo.org/",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "ASEAN",
    path: "https://asean.org/",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "CACCI",
    path: "https://www.cacci.biz/",
    cName: "dropdown_item",
    parent: "international-affairs",
  },
  {
    title: "Local Chambers",
    path: "/membership/local-chambers",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "2021 New Members",
    path: "/new-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Charter Members",
    path: "/charter-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Life Members",
    path: "/life-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Regular (Direct) Members",
    path: "/regular-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Association Members",
    path: "/association-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Affiliate Members",
    path: "/affiliate-members",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "How To Join",
    path: "/how-to-join",
    cName: "dropdown_item",
    parent: "membership",
  },
  {
    title: "Alternative Dispute Resolution",
    path: "/alternative-dispute-resolution",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "APEC Business Travel Card",
    path: "/apec-business-travel-card",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "FICCI Business Offers",
    path: "/ficci-business-offers",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Business Opportunities",
    path: "/business-opportunities",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Certificate of Origin",
    path: "/certificate-of-origin",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Corporate Social Responsibility",
    path: "/csr",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Market Encounter Goes to Manila",
    path: "/market-encounter",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Trade Fairs",
    path: "/trade-fairs",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
  {
    title: "Trainings and Seminars",
    path: "/trainings-and-seminars",
    cName: "dropdown_item",
    parent: "programs-and-services",
  },
];
