export const MenuItems = [
  {
    title: "History",
    path: "/history",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "What can PCCI do for you",
    path: "/what-can-pcci-do-for-you",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Board Of Directors",
    path: "/board-of-directors",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Secretariat",
    path: "/secretariat",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Contact Us",
    path: "/contact-us",
    cName: "dropdown_item",
    parent: "about",
  },
  {
    title: "Agriculture and Fishery",
    path: "/agriculture-and-fishery",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Banking and Capital Formation",
    path: "/banking-and-capital-formation",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Corporate Governance",
    path: "/corporate-governance",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Energy and Power",
    path: "/energy-and-power",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Industry and Trade",
    path: "/industry-and-trade",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Infrastructure",
    path: "/infrastructure",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Innovation and Science and Technology",
    path: "/innovation-and-science-and-technology",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Intellectual Property",
    path: "/intellectual-property",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Legislation and Taxation",
    path: "/legislation-and-taxation",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Mining and Mineral Resources",
    path: "/mining-and-mineral-resources",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Sustainable Development Goals",
    path: "/sustainable-development-goals",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Transport Logistics",
    path: "/transport-logistics",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Urban Housing Development",
    path: "/urban-housing-development",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "Youth",
    path: "/youth",
    cName: "dropdown_item",
    parent: "advocacy",
  },
  {
    title: "PCCI Innovation Center",
    path: "/pcci-innovation-center",
    cName: "dropdown_item",
    parent: "advocacy",
  },
];
