import Head from "next/head";

const Meta = ({ title, description }) => {
  return (
    <Head>
      <title>{`${title} | Philippine Chamber of Commerce and Industry`}</title>
      <meta name={description} content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link
        rel='preconnect'
        href='https://fonts.gstatic.com'
        crossOrigin='true'
      />
      <link
        href='https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'
        rel='stylesheet'
      />
    </Head>
  );
};

Meta.defaultProps = {
  title: "Home",
  description:
    "The Philippine Chamber of Commerce and Industry is a non-government association of private businesses that works to influence government actions on issues such as Agriculture, Information Technology, Human Resources, and Tourism.",
};

export default Meta;
