import Head from "next/head";

const Meta = ({ title, description }) => {
  return (
    <Head>
      <title>{`${title} | Philippine Chamber of Commerce and Industry`}</title>
      <meta name={description} content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

Meta.defaultProps = {
  title: "Home",
  description:
    "The Philippine Chamber of Commerce and Industry is a non-government association of private businesses that works to influence government actions on issues such as Agriculture, Information Technology, Human Resources, and Tourism.",
};

export default Meta;
